#!/command/with-contenv sh

## Defaults

SCRIPT_NAME="jvm-args"

## Main

# Default combined JVM args
JVM_COMBINED=""

# If JVM_XMS is set
if [ -n "${JVM_XMS}" ]; then
  JVM_COMBINED="${JVM_COMBINED}-Xms${JVM_XMS} "
fi

# If JVM_XMX is set
if [ -n "${JVM_XMX}" ]; then
  JVM_COMBINED="${JVM_COMBINED}-Xmx${JVM_XMX} "
fi

# If JVM_EXTRA_VARS is set
if [ -n "${JVM_EXTRA_VARS}" ]; then
  JVM_COMBINED="${JVM_COMBINED}${JVM_EXTRA_VARS} "
fi

# Check if JVM_COMBINED has any parameter
if [ -n "${JVM_COMBINED}" ]; then

  # Setup JVM args
  printf -- '%s: info: setup JVM args to: %s\n' "${SCRIPT_NAME}" "${JVM_COMBINED}"
  printf -- '%s\n' "${JVM_COMBINED}" \
  > "${APP_DIR}/user_jvm_args.txt"

else

  printf -- '%s: info: no JVM args set\n' "${SCRIPT_NAME}"
  
fi