#!/command/with-contenv sh

## Defaults

SCRIPT_NAME="mc-accept-eula"

eula_file="eula.txt"

## Main

# If ACCEPT_EULA is true
if [ "${ACCEPT_EULA}" = "true" ]; then

  # Wait until file exists
  printf -- '%s: info: checking %s\n' "${SCRIPT_NAME}" "${eula_file}"
  until [ -f "${DATA_DIR}/${eula_file}" ]
  do
    sleep 0.5
  done

  # Create regexp and replacement for sed
  regexp="^eula=.*$"
  replacement="eula=true"

  # If eula already true, skip
  if ! grep -q "^${replacement}$" "${DATA_DIR}/${eula_file}"; then

    # Setting eula=true
    printf -- '%s: info: setting %s\n' "${SCRIPT_NAME}" "${replacement}"
    sed -i "s/${regexp}/${replacement}/g" "${DATA_DIR}/${eula_file}"

  fi
fi
