#!/command/with-contenv sh

# Change group and user ids
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

printf -- '
-------------------------------------
GID/UID
-------------------------------------
User uid:    %s
User gid:    %s
-------------------------------------
' "$(id -u abc)" "$(id -g abc)"

# Set correct ownership on app folders
chown -R "$PUID:$PGID" "$APP_DIR"
chown -R "$PUID:$PGID" "$DATA_DIR"
