name: Publish Docker image

on:
  push
#  release:
#    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Split minecraft and forge versions
        id: split
        uses: actions/github-script@v6
        with:
          script: |
            const version = context.github.ref_name.split('-')
            core.setOutput('version', version[0])
      - run: echo "${{ steps.split.outputs.version }}"
      - run: echo "${{ steps.split.outputs.result }}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server-forge
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}}
            type=semver,pattern={{major}},prefix=v
            type=sha

      - name: Get build args from build.env
        id: extra-build-args
        run: |
          # Get env vars from build.env and remove comments, empty lines, trim
          args=$(cat build.env | sed -e 's/#.*//' -e 's/[ ^I]*$//' -e '/^$/ d')
          
          # Convert multiline to json
          args=$(printf -- '%s' "${args}" | jq --raw-input --slurp '.')
          
          echo "::set-output name=args::${args}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.documentation=${{ join(fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.url'], '/blob/main/README.md') }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            ${{ fromJSON(steps.extra-build-args.outputs.args) }}