name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: adripo/minecraft-server-forge
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Get build args from build.env
        id: extra-build-args
        run: |
          args=$(cat build.env | sed -e 's/#.*//' -e 's/[ ^I]*$//' -e '/^$/ d')
          args="${args//$'\n'/'%0A'}"
          echo "::set-output name=args::${args}"

      - name: Get current date
        id: date
        run: |
          date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "::set-output name=date::${date}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            ${{ steps.extra-build-args.outputs.args }}